# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdetails',
            old_name='datetime',
            new_name='appointmenttime',
        ),
    ]
