# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atservices', '0002_auto_20180329_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='appointmenttime',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
